/**
 * Copyright (c) 2026 tbaur
 *
 * Licensed under the Apache License, Version 2.0
 * See LICENSE file for full license text
 *
 * @fileoverview Homebridge dynamic platform for AudioControl Concert XR receivers.
 */

import type {
  API,
  Characteristic as CharacteristicClass,
  DynamicPlatformPlugin,
  Logging,
  PlatformAccessory,
  PlatformConfig,
  Service as ServiceClass,
} from 'homebridge'

import { ConcertClient } from './api'
import { PowerAccessory, SourcePresetAccessory, VolumePresetAccessory } from './devices'
import {
  DEFAULT_MODEL,
  DEFAULT_REFRESH_RATE_SEC,
  PLATFORM_NAME,
  PLUGIN_NAME,
  UUID_PREFIX,
  readPluginVersion,
} from './settings'
import type {
  AccessoryContext,
  ConcertPlatformConfig,
  RefreshReason,
  RefreshableAccessory,
  ResolvedAccessory,
} from './types'
import {
  accessoryIdentityKey,
  describeError,
  forLog,
  newAccessorySerialNumber,
  resolveAccessories,
  resolvePort,
  resolveRefreshRateSec,
  validateConfig,
} from './utils'

/**
 * True when a cached accessory context describes the same switch as `config`.
 *
 * Identity is what the switch does — kind, zone, and the preset target — which
 * is exactly what the UUID is derived from. Used to re-adopt accessories whose
 * UUID was generated by an earlier scheme.
 */
/** True when a previous launch already recorded this accessory as adopted. */
function wasAdoptionRecorded(context: unknown): boolean {
  return (context as Partial<AccessoryContext> | undefined)?.adoptedLegacyUuid === true
}

function hasAccessoryIdentity(context: unknown, config: ResolvedAccessory): boolean {
  const cached = context as Partial<AccessoryContext> | undefined
  if (!cached || cached.kind !== config.kind || cached.zone !== config.zone) {
    return false
  }
  if (config.kind === 'volumePreset') {
    return cached.volume === config.volume
  }
  if (config.kind === 'sourcePreset') {
    return cached.source === config.source
  }
  return true
}

/**
 * Registers configured Switch accessories for a Concert receiver and polls
 * their state on a shared timer.
 */
export default class ConcertPlatform implements DynamicPlatformPlugin {
  public readonly Service: typeof ServiceClass
  public readonly Characteristic: typeof CharacteristicClass
  public readonly accessories: PlatformAccessory[] = []

  private readonly config: ConcertPlatformConfig
  /** Polled first so presets see a fresh power state before deciding to skip. */
  private readonly powerHandlers: RefreshableAccessory[] = []
  /** Volume/source presets, polled together so same-zone queries coalesce. */
  private readonly presetHandlers: RefreshableAccessory[] = []
  private client?: ConcertClient
  private pollTimer?: ReturnType<typeof setInterval>
  /** In-flight shared poll; overlapping timer ticks join/skip instead of stacking. */
  private refreshAllInFlight?: Promise<void>
  /** Reason governing the in-flight walk; a joining poll upgrades it. */
  private refreshAllReason: RefreshReason = 'poll'
  /** A post-set refresh arrived mid-walk and needs a pass of its own. */
  private refreshAgainWhenDone = false
  private stopped = false
  /** True when startup validation failed; the platform stays inert. */
  private disabled = false

  /**
   * @param config - Whatever Homebridge read from `config.json`. Typed as the
   *   generic `PlatformConfig` rather than {@link ConcertPlatformConfig} because
   *   nothing has validated it yet, and because a narrower parameter type does
   *   not satisfy Homebridge's `PlatformPluginConstructor`.
   */
  constructor(
    public readonly log: Logging,
    config: PlatformConfig,
    public readonly api: API,
  ) {
    this.Service = api.hap.Service
    this.Characteristic = api.hap.Characteristic
    this.config = config as ConcertPlatformConfig

    // Validated through the narrowed alias; `validateConfig` re-checks every
    // field, so the cast above asserts nothing this does not verify.
    const { errors, warnings } = validateConfig(this.config)
    for (const warning of warnings) {
      this.log.warn(warning)
    }
    if (errors.length > 0) {
      for (const error of errors) {
        this.log.error(error)
      }
      this.log.error('Invalid configuration; plugin will not start until it is corrected.')
      this.disabled = true
    } else {
      this.log.info(`Initializing ${this.config.name ?? PLATFORM_NAME} platform`)
    }

    // Always register lifecycle handlers so a disabled platform can still clear
    // orphaned cached accessories and shut down cleanly.
    this.api.on('didFinishLaunching', () => {
      if (this.stopped) {
        return
      }
      // Anything thrown here would escape into Homebridge's event emitter and
      // take down the host process along with every other plugin, so the whole
      // body is guarded rather than just the discovery call.
      try {
        if (this.disabled) {
          this.reportInactiveAccessories()
          return
        }
        this.discoverDevices()
      } catch (error) {
        // Not necessarily a config problem — HAP registration can fail too — so
        // the message points at the error above rather than at config.json.
        this.log.error(`Failed to set up accessories: ${describeError(error)}`)
        this.log.error('Plugin is inactive. Resolve the error above and restart Homebridge.')
        this.disabled = true
        this.stopPolling()
      }
    })

    this.api.on('shutdown', () => {
      this.stopPolling()
    })
  }

  /**
   * Restore a cached accessory from disk. Handlers are attached later during
   * discovery so we only keep a reference here.
   */
  configureAccessory(accessory: PlatformAccessory): void {
    this.log.info(`Loading cached accessory: ${forLog(accessory.displayName)}`)
    this.accessories.push(accessory)
  }

  /** Stop the poll timer, release client resources, and mark the platform stopped. */
  private stopPolling(): void {
    this.stopped = true
    if (this.pollTimer) {
      clearInterval(this.pollTimer)
      this.pollTimer = undefined
    }
    this.refreshAllInFlight = undefined
    this.client?.close()
  }

  /**
   * Explain that cached accessories are present but unusable.
   *
   * They are deliberately left registered: unregistering makes HomeKit discard
   * room assignments, scene membership, and automations, which the user cannot
   * recover by fixing the config. Leaving them registered means they report
   * "No Response" until the configuration is valid again.
   */
  private reportInactiveAccessories(): void {
    if (this.accessories.length === 0) {
      return
    }
    this.log.warn(
      `${this.accessories.length} cached accessory(ies) will report No Response `
      + 'until the configuration is corrected.',
    )
    for (const accessory of this.accessories) {
      this.markAccessoryUnavailable(accessory)
    }
  }

  /**
   * Create or update Switch accessories for each configured entry and start
   * polling their state.
   */
  private discoverDevices(): void {
    const host = this.config.host.trim()
    const port = resolvePort(this.config.port)
    const model = (this.config.model?.trim() || DEFAULT_MODEL)
    const resolved = resolveAccessories(this.config)

    // The single most useful line in a bug report: which build, talking to what.
    this.log.info(
      `homebridge-concert v${readPluginVersion(this.log)} → ${host}:${port} (${model})`,
    )

    // Pair before pruning: an adopted accessory keeps its original UUID, which
    // must therefore count as one to keep.
    const pairs = this.pairWithCached(resolved)
    const keepUuids = new Set(
      resolved.map((accessory) => pairs.get(accessory)?.UUID ?? this.uuidFor(accessory)),
    )
    this.removeStaleAccessories(keepUuids)

    this.client = new ConcertClient({
      host,
      port,
      logger: this.log,
    })
    this.powerHandlers.length = 0
    this.presetHandlers.length = 0

    // Power first so a poll tick observes standby before volume/source decide
    // whether to skip.
    const ordered = [
      ...resolved.filter((accessory) => accessory.kind === 'power'),
      ...resolved.filter((accessory) => accessory.kind !== 'power'),
    ]

    const target = { host, port, model }
    for (const accessoryConfig of ordered) {
      // One accessory that fails must not prevent the others from working. If it
      // was already registered it stays registered, so HomeKit keeps its room and
      // scenes, but with failing handlers so it reads as No Response rather than
      // serving the stale value HAP would otherwise return from its cache.
      let accessory: PlatformAccessory | undefined
      try {
        accessory = this.syncAccessory(accessoryConfig, target, pairs.get(accessoryConfig))
        const handler = this.createHandler(accessoryConfig, accessory, this.client)
        const group = accessoryConfig.kind === 'power' ? this.powerHandlers : this.presetHandlers
        group.push(handler)
      } catch (error) {
        this.log.error(
          `Skipping accessory "${accessoryConfig.name}": ${describeError(error)}`,
        )
        if (accessory) {
          this.markAccessoryUnavailable(accessory)
        }
      }
    }

    if (this.powerHandlers.length + this.presetHandlers.length === 0) {
      this.log.error('No accessories could be set up; nothing will be polled.')
      return
    }

    this.startPolling()
    this.startRefreshAll()
  }

  /**
   * Pair each configured accessory with the cached accessory it should reuse.
   *
   * Exact UUID matches are claimed first, then any remaining entry falls back to
   * the identity recorded in the cached context. That fallback is a migration
   * path: UUIDs used to be seeded with `host:port`, so an accessory cached by an
   * earlier version has a different UUID for the same switch. Adopting it keeps
   * the user's room assignment, scenes, and automations across the upgrade
   * instead of silently replacing every switch.
   */
  private pairWithCached(
    resolved: readonly ResolvedAccessory[],
  ): Map<ResolvedAccessory, PlatformAccessory> {
    const pairs = new Map<ResolvedAccessory, PlatformAccessory>()
    const claimed = new Set<string>()

    for (const accessoryConfig of resolved) {
      const uuid = this.uuidFor(accessoryConfig)
      const exact = this.accessories.find(
        (cached) => cached.UUID === uuid && !claimed.has(cached.UUID),
      )
      if (exact) {
        pairs.set(accessoryConfig, exact)
        claimed.add(exact.UUID)
      }
    }

    for (const accessoryConfig of resolved) {
      if (pairs.has(accessoryConfig)) {
        continue
      }
      const adopted = this.accessories.find(
        (cached) => !claimed.has(cached.UUID)
          && hasAccessoryIdentity(cached.context, accessoryConfig),
      )
      if (!adopted) {
        continue
      }
      // Announced once. The adopted accessory keeps its legacy UUID forever, so
      // this path runs on every launch; repeating the notice would imply an
      // upgrade is happening each time.
      const message = `Adopting cached accessory "${forLog(adopted.displayName)}" for `
        + `${accessoryIdentityKey(accessoryConfig)}`
      if (wasAdoptionRecorded(adopted.context)) {
        this.log.debug(`${message} (identity predates the current scheme)`)
      } else {
        this.log.info(`${message} (registered by an earlier version)`)
      }
      pairs.set(accessoryConfig, adopted)
      claimed.add(adopted.UUID)
    }

    return pairs
  }

  /**
   * Register a new accessory or bring a cached one up to date.
   *
   * @param target - Current receiver address and model from config
   * @param existing - Cached accessory this entry was paired with, if any
   * @returns the live PlatformAccessory for this configured entry
   */
  private syncAccessory(
    accessoryConfig: ResolvedAccessory,
    target: { host: string; port: number; model: string },
    existing: PlatformAccessory | undefined,
  ): PlatformAccessory {
    const { host, port, model } = target
    const uuid = this.uuidFor(accessoryConfig)
    const previous = existing?.context as AccessoryContext | undefined
    const previousSerial = previous?.serialNumber
    const context: AccessoryContext = {
      kind: accessoryConfig.kind,
      host,
      port,
      zone: accessoryConfig.zone,
      model,
      serialNumber: typeof previousSerial === 'string' && previousSerial.length > 0
        ? previousSerial
        : newAccessorySerialNumber(),
      // Persisted so the next launch knows this adoption is already established.
      adoptedLegacyUuid: existing !== undefined && existing.UUID !== uuid,
      volume: accessoryConfig.volume,
      source: accessoryConfig.source,
    }

    if (!existing) {
      this.log.info(
        `Registering accessory "${accessoryConfig.name}" `
        + `(${accessoryIdentityKey(accessoryConfig)}) at ${host}:${port}`,
      )
      const accessory = new this.api.platformAccessory(accessoryConfig.name, uuid)
      accessory.context = context
      this.api.registerPlatformAccessories(PLUGIN_NAME, PLATFORM_NAME, [accessory])
      this.accessories.push(accessory)
      return accessory
    }

    this.logHostChange(existing, previous, host, port)
    existing.context = context
    this.applyAccessoryDisplayName(existing, accessoryConfig.name)
    this.api.updatePlatformAccessories([existing])
    this.log.info(
      `Restored accessory "${accessoryConfig.name}" `
      + `(${accessoryIdentityKey(accessoryConfig)}) at ${host}:${port}`,
    )
    return existing
  }

  /**
   * Make an accessory read as "No Response" in the Home app.
   *
   * An accessory with no handler still answers reads: HAP falls back to the value
   * deserialized from its cache (`Characteristic.handleGetRequest`), so the switch
   * would show a stale state that an automation could act on. Handlers that fail
   * turn that into an honest no-response.
   */
  private markAccessoryUnavailable(accessory: PlatformAccessory): void {
    // Restored from disk by another plugin version, so treat the shape as untrusted.
    const service = typeof accessory.getService === 'function'
      ? accessory.getService(this.Service.Switch)
      : undefined
    if (!service) {
      return
    }
    const unavailable = (): never => {
      throw new this.api.hap.HapStatusError(
        this.api.hap.HAPStatus.SERVICE_COMMUNICATION_FAILURE,
      )
    }
    service.getCharacteristic(this.Characteristic.On)
      .onGet(unavailable)
      .onSet(unavailable)
  }

  private createHandler(
    config: ResolvedAccessory,
    accessory: PlatformAccessory,
    client: ConcertClient,
  ): RefreshableAccessory {
    // Exhaustive on purpose: a new AccessoryKind should fail to compile rather
    // than fall through to a handler that throws at runtime.
    switch (config.kind) {
      case 'power':
        return new PowerAccessory(this, accessory, client)
      case 'sourcePreset':
        return new SourcePresetAccessory(this, accessory, client)
      case 'volumePreset':
        return new VolumePresetAccessory(this, accessory, client)
      default: {
        const unhandled: never = config.kind
        throw new Error(`Unsupported accessory kind: ${String(unhandled)}`)
      }
    }
  }

  /**
   * Stable HomeKit identity for a configured accessory.
   *
   * Deliberately excludes host and port. Seeding the UUID with the address meant
   * a DHCP lease change produced entirely new accessories, so `removeStaleAccessories`
   * unregistered the old ones and the user lost every room assignment, scene, and
   * automation — for a receiver that had simply moved. Identity is what the switch
   * *does*; the address is configuration.
   */
  private uuidFor(accessory: ResolvedAccessory): string {
    return this.api.hap.uuid.generate(`${UUID_PREFIX}${accessoryIdentityKey(accessory)}`)
  }

  /**
   * Sync the accessory display name onto the PlatformAccessory wrapper and the
   * underlying HAP accessory. Assigning `displayName` alone does not update what
   * Homebridge serializes / publishes after cache restore — use `updateDisplayName`
   * when available (Homebridge ≥1.8).
   */
  private applyAccessoryDisplayName(accessory: PlatformAccessory, name: string): void {
    if (accessory.displayName === name) {
      return
    }
    const previous = accessory.displayName
    // Both members are declared optional here so this compiles against
    // Homebridge 1.6 (no `updateDisplayName`) and 2.x alike.
    const legacy = accessory as PlatformAccessory & {
      updateDisplayName?: (value: string) => void
      _associatedHAPAccessory?: { displayName?: string }
    }
    if (typeof legacy.updateDisplayName === 'function') {
      legacy.updateDisplayName(name)
    } else {
      accessory.displayName = name
      if (legacy._associatedHAPAccessory) {
        legacy._associatedHAPAccessory.displayName = name
      }
    }
    this.log.info(`Renamed accessory "${previous}" → "${name}"`)
  }

  /**
   * Note when a cached accessory's receiver address has changed.
   *
   * The previous target is the only reason the cache records host and port; a
   * DHCP lease that moved is a common cause of "everything stopped working".
   */
  private logHostChange(
    accessory: PlatformAccessory,
    previous: AccessoryContext | undefined,
    host: string,
    port: number,
  ): void {
    if (!previous?.host) {
      return
    }
    if (previous.host === host && previous.port === port) {
      return
    }
    this.log.info(
      `${accessory.displayName}: receiver address changed `
      + `${forLog(previous.host)}:${forLog(previous.port)} → ${host}:${port}`,
    )
  }

  /** Unregister cached accessories that are no longer in the configured set. */
  private removeStaleAccessories(keepUuids: Set<string>): void {
    const stale = this.accessories.filter((accessory) => !keepUuids.has(accessory.UUID))
    if (stale.length === 0) {
      return
    }
    for (const accessory of stale) {
      this.log.info(`Removing stale accessory: ${forLog(accessory.displayName)}`)
    }
    this.api.unregisterPlatformAccessories(PLUGIN_NAME, PLATFORM_NAME, stale)
    for (const accessory of stale) {
      const index = this.accessories.indexOf(accessory)
      if (index >= 0) {
        this.accessories.splice(index, 1)
      }
    }
  }

  private startPolling(): void {
    if (this.pollTimer) {
      clearInterval(this.pollTimer)
    }
    const refreshSec = resolveRefreshRateSec(
      this.config.options?.refreshRate,
      DEFAULT_REFRESH_RATE_SEC,
    )
    this.log.info(`Polling accessory state every ${refreshSec}s`)
    this.pollTimer = setInterval(() => {
      this.startRefreshAll()
    }, refreshSec * 1000)
    // The host owns the process lifecycle; our poll timer must not hold it open.
    this.pollTimer.unref?.()
  }

  /**
   * Re-read every accessory now.
   *
   * Called after a successful set, because one accessory's write changes what
   * its siblings should report: only one volume level or input can be active,
   * and a preset set implies the receiver is awake.
   */
  requestRefresh(): void {
    this.startRefreshAll('post-set')
  }

  /**
   * Kick off a refresh without awaiting it.
   *
   * An unhandled rejection here would terminate the whole Homebridge process
   * under Node's default `--unhandled-rejections=throw`, so the promise always
   * gets a handler.
   */
  private startRefreshAll(reason: RefreshReason = 'poll'): void {
    this.refreshAll(reason).catch((error: unknown) => {
      this.log.error(`Unexpected failure while refreshing accessories: ${describeError(error)}`)
    })
  }

  /**
   * Refresh power first, then the presets. Power is awaited so presets see an
   * updated last-known power state before deciding whether to skip.
   *
   * Single-flight: a timer tick that fires while a previous refresh is still
   * running joins that promise instead of starting a second walk (important when
   * refreshRate is low and a standby timeout makes one tick last several seconds).
   */
  private refreshAll(reason: RefreshReason): Promise<void> {
    if (this.stopped || this.powerHandlers.length + this.presetHandlers.length === 0) {
      return Promise.resolve()
    }
    if (this.refreshAllInFlight) {
      this.log.debug(`Refresh (${reason}) coalesced; previous refresh still in flight`)
      // A scheduled poll is the stricter reason: its failures are real news, so
      // joining a post-set walk must not inherit that walk's leniency.
      if (reason === 'poll') {
        this.refreshAllReason = 'poll'
      }
      // The in-flight walk may already have read the accessories this set just
      // invalidated, so queue a trailing pass rather than silently joining.
      if (reason === 'post-set') {
        this.refreshAgainWhenDone = true
      }
      return this.refreshAllInFlight
    }

    this.refreshAllReason = reason
    this.refreshAllInFlight = this.runRefreshAll().finally(() => {
      this.refreshAllInFlight = undefined
      if (this.refreshAgainWhenDone && !this.stopped) {
        this.refreshAgainWhenDone = false
        this.startRefreshAll('post-set')
      }
    })
    return this.refreshAllInFlight
  }

  private async runRefreshAll(): Promise<void> {
    for (const handler of this.powerHandlers) {
      if (this.stopped) {
        return
      }
      await this.refreshOne(handler)
    }
    if (this.stopped) {
      return
    }
    // Presets refresh together so the client's per-zone in-flight coalescing
    // collapses several presets on one zone into a single query. Refreshing
    // them one at a time defeats that and costs one TCP round trip each.
    await Promise.all(this.presetHandlers.map((handler) => this.refreshOne(handler)))
  }

  /**
   * Refresh one handler; a handler that throws must not abort the whole walk.
   *
   * The reason is read here rather than passed down so a poll that coalesced onto
   * an in-flight walk still gets poll-strength failure reporting.
   */
  private async refreshOne(handler: RefreshableAccessory): Promise<void> {
    try {
      await handler.refresh(this.refreshAllReason)
    } catch (error) {
      this.log.error(`Accessory refresh failed unexpectedly: ${describeError(error)}`)
    }
  }
}
